started.
  0%|          | 0/1056 [00:00<?, ?it/s]  0%|          | 0/1056 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    trainCM_Issolation(model=model,ema_model=ema_model,img_channels=img_channels,dataloader=dataloader,n_epochs=n_epochs,dbname=dbname,  lr=lr, device= device,hideProgressBar=False)
  File "/home/mgokmen/Projects/consisteny_model_unofficial/functions.py", line 70, in trainCM_Issolation
    loss_model = calculate_loss(x, z, t_0, t_1,model=model, ema_model=ema_model)
  File "/home/mgokmen/Projects/consisteny_model_unofficial/functions.py", line 16, in calculate_loss
    x2 = model(x2, t2)
  File "/home/mgokmen/Projects/consisteny_model_unofficial/myvenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mgokmen/Projects/consisteny_model_unofficial/myvenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mgokmen/Projects/consisteny_model_unofficial/myvenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/home/mgokmen/Projects/consisteny_model_unofficial/myvenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/mgokmen/Projects/consisteny_model_unofficial/myvenv/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 110, in parallel_apply
    output.reraise()
  File "/home/mgokmen/Projects/consisteny_model_unofficial/myvenv/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/mgokmen/Projects/consisteny_model_unofficial/myvenv/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
  File "/home/mgokmen/Projects/consisteny_model_unofficial/myvenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mgokmen/Projects/consisteny_model_unofficial/myvenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mgokmen/Projects/consisteny_model_unofficial/model/unet.py", line 101, in forward
    x= self.conv_input(x)
  File "/home/mgokmen/Projects/consisteny_model_unofficial/myvenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mgokmen/Projects/consisteny_model_unofficial/myvenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mgokmen/Projects/consisteny_model_unofficial/myvenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/mgokmen/Projects/consisteny_model_unofficial/myvenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (c10::Half) and bias type (float) should be the same

